#!/bin/bash

echo "Generate README.adoc from Antora docs"

pwd
ls -alF

echo "= $1" > README.adoc
{
cat docs/modules/ROOT/partials/vars.adoc
echo
echo "// +-----------------------------------------+"
echo "// |                                         |"
echo "// |    DO NOT EDIT DIRECTLY !!!!!           |"
echo "// |                                         |"
echo "// |    File is auto-generated by pipline    |"
echo "// |    Contents are based on Antora docs    |"
echo "// |                                         |"
echo "// +-----------------------------------------+"
echo
cat docs/modules/ROOT/partials/README.adoc
echo
} >> README.adoc

cat README.adoc
